function [ UIFigure, MethodDropDown, NameEdit, ...
    WholeCheckBox, PhasesCheckBox, ReigonStatisticPanel, ...
    ReigonButtonGroup, StageCheckBox, GrainPartitionCheckBox, ...
    GrainPartitionPanel, GrainPartitionCoeffSpinner, GrainPartitionShowCheckBox, ...
    ConfirmButton ] = createStatisticButton_UI( app )


DisplayNames = app.OtherDisplayNames( app.Default.LanguageSelection );
ButtonSize = app.ConstantValues.TextedButtonSize;
DropDownHeight = app.ConstantValues.DropDownHeight;
UIFigureSize = [300,280];
PanelHeight_2 = 75;
PanelWidth_1 = 140;
LabelWidth = 30;
EditWidth = 60;
LabelHeight = 15;

% ---------- UIFigure ----------
UIFigure = uifigure( ...
    'Name', DisplayNames.StatisticButton_UIFigure, ...
    'WindowStyle', 'modal', ...alwaysontop
    'Icon', app.ConstantValues.IconSource, ...
    'Resize', 'off' );
UIFigure.Position = getMiddlePosition( ...
    app.UIFigure.Position, UIFigureSize );


% ---------- GridLayoutMain ----------
GridLayoutMain = uigridlayout( UIFigure, ...
    'RowHeight', { DropDownHeight, '1x', ButtonSize(2) }, ...
    'ColumnWidth',  { '1x' }, ...
    'Padding',      15*ones(1,4));


% ---------- GridLayoutName ----------
GridLayoutName = uigridlayout( GridLayoutMain, ...
    'ColumnWidth', { LabelWidth, EditWidth, LabelWidth, '1x' }, ...
    'RowHeight', { '1x' }, ...
    'Padding', 0*[1,1,1,1] );
GridLayoutName.Layout.Row = 1;

% ---------- NameLabel ----------
NameLabel = uilabel( GridLayoutName, ...
    'Text', DisplayNames.cm_Name, ...
    'HorizontalAlignment', 'center' );
NameLabel.Layout.Column = 1;

% ---------- NameEdit ----------
NameEdit = uieditfield( GridLayoutName );
NameEdit.Layout.Column = 2;

% ---------- MethodLabel ----------
MethodLabel = uilabel( GridLayoutName, ...
    'Text', DisplayNames.StatisticButton_MethodLabel, ...
    'HorizontalAlignment', 'center' );
MethodLabel.Layout.Column = 3;

% ---------- MethodDropDown ----------
MethodDropDown = uidropdown( GridLayoutName );
MethodDropDown.Layout.Column = 4;
Items = {{'Line Probe (Value)','Reigon Statistic (Frequency)'}, ...
    {'线测量（值）','区域统计（频率）'}};
MethodDropDown.Items = Items{ app.Default.LanguageSelection };
MethodDropDown.ItemsData = { 'line', 'reigon' };


% ---------- GridLayoutTemp ----------
GridLayoutTemp = uigridlayout( GridLayoutMain, ...
    'ColumnWidth', { PanelWidth_1, '1x' }, ...
    'RowHeight', { '1x', PanelHeight_2 }, ...
    'Padding', 0*[1,1,1,1] );
GridLayoutTemp.Layout.Row = 2;


% ---------- IncludePanel ----------
IncludePanel = uipanel( GridLayoutTemp, ...
    "Title", DisplayNames.StatisticButton_IncludePanel );
IncludePanel.Layout.Column = 1;
IncludePanel.Layout.Row = 1;

% ---------- GridLayoutInclude ----------
GridLayoutInclude = uigridlayout( IncludePanel, ...
    'ColumnWidth', {'2x','3x'}, ...
    'RowHeight', { LabelHeight, LabelHeight }, ...
    'Padding', 10*[1,1,1,1] );

% ---------- WholeCheckBox ----------
WholeCheckBox = uicheckbox( GridLayoutInclude, ...
    'Text', DisplayNames.StatisticButton_WholeCheckBox, ...
    'Value', true, ...
    'Tag', 'whole'  );
WholeCheckBox.Layout.Row = 1;
WholeCheckBox.Layout.Column = 1;

% ---------- PhasesCheckBox ----------
PhasesCheckBox = uicheckbox( GridLayoutInclude, ...
    'Text', DisplayNames.StatisticButton_PhasesCheckBox, ...
    'Value', false, ...
    'Tag', 'phases'  );
PhasesCheckBox.Layout.Row = 2;
PhasesCheckBox.Layout.Column = 1;

% ---------- StageCheckBox ----------
StageCheckBox = uicheckbox( GridLayoutInclude, ...
    'Text', DisplayNames.StatisticButton_StageCheckBox, ...
    'Value', false, ...
    'Tag', 'stage' );
StageCheckBox.Layout.Row = 1;
StageCheckBox.Layout.Column = 2;

% ---------- GrainPartitionCheckBox ----------
GrainPartitionCheckBox = uicheckbox( GridLayoutInclude, ...
    'Text', DisplayNames.StatisticButton_GrainPartitionCheckBox, ...
    'Value', false, ...
    'Tag', 'stage', ...
    'Enable', false );
GrainPartitionCheckBox.Layout.Row = 2;
GrainPartitionCheckBox.Layout.Column = 2;

% ---------- ReigonStatisticPanel ----------
ReigonStatisticPanel = uipanel( GridLayoutTemp, ...
    "Title", MethodDropDown.Items{2}, ...
    'Enable', 'off' );
ReigonStatisticPanel.Layout.Column = 2;
ReigonStatisticPanel.Layout.Row = 1;

% ---------- GridLayoutReigonStatistic ----------
GridLayoutReigonStatistic = uigridlayout( ReigonStatisticPanel, ...
    'ColumnWidth', { '1x' }, ...
    'RowHeight', { '1x' }, ...
    'Padding', 5*[1,1,1,1] );

% ---------- ReigonButtonGroup ----------
ReigonButtonGroup = uibuttongroup( GridLayoutReigonStatistic, ...
    'BorderType', 'none' );

% ---------- SelectRadioButton ----------
SelectRadioButton = uiradiobutton( ReigonButtonGroup, ...
    'Text', DisplayNames.StatisticButton_SelectRadioButton, ...
    'UserData', 'select' );
SelectRadioButton.Position(1) = 5;
SelectRadioButton.Position(2) = 5;

% ---------- WholeRadioButton ----------
WholeRadioButton = uiradiobutton( ReigonButtonGroup, ...
    'Text', DisplayNames.StatisticButton_WholeRadioButton, ...
    'UserData', 'whole' );
WholeRadioButton.Position(1) = 5;
WholeRadioButton.Position(2) = 25;

% ---------- GrainPartitionPanel ----------
GrainPartitionPanel = uipanel( GridLayoutTemp, ...
    "Title", DisplayNames.StatisticButton_GrainPartitionCheckBox, ...
    'Enable', 'off' );
GrainPartitionPanel.Layout.Row = 2;
GrainPartitionPanel.Layout.Column = 2;

% ---------- GridLayoutGrainPartition ----------
GridLayoutGrainPartition = uigridlayout( GrainPartitionPanel, ...
    'ColumnWidth', { LabelWidth, '1x' }, ...
    'RowHeight', { '1x', LabelHeight }, ...
    'RowSpacing', 5, ...
    'Padding', 10*[1,0.5,1,0.5] );

% ---------- GrainPartitionCoeffLabel ----------
GrainPartitionCoeffLabel = uilabel( GridLayoutGrainPartition, ...
    'Text', DisplayNames.StyleButton_CLimCoeffLabel, ...
    'HorizontalAlignment', 'center' );
GrainPartitionCoeffLabel.Layout.Row = 1;
GrainPartitionCoeffLabel.Layout.Column = 1;

% ---------- GrainPartitionCoeffSpinner ----------
GrainPartitionCoeffSpinner = uispinner( GridLayoutGrainPartition );
GrainPartitionCoeffSpinner.Layout.Row = 1;
GrainPartitionCoeffSpinner.Layout.Column = 2;

% ---------- GrainPartitionShowCheckBox ----------
GrainPartitionShowCheckBox = uicheckbox( GridLayoutGrainPartition, ...
    'Text', DisplayNames.StatisticButton_GrainPartitionShowCheckBox, ...
    'Value', false, ...
    'Tag', 'stage' );
GrainPartitionShowCheckBox.Layout.Row = 2;
GrainPartitionShowCheckBox.Layout.Column = [1,2];

% ---------- GridLayoutButtons ----------
GridLayoutButtons = uigridlayout( GridLayoutMain, ...
    'RowHeight',    { '1x' }, ...
    'ColumnWidth',  { '1x', ButtonSize(1), ButtonSize(1) }, ...
    'Padding', zeros(1,4) );
GridLayoutButtons.Layout.Row = 3;

% ---------- ConfirmButton * ----------
ConfirmButton = uibutton( GridLayoutButtons, 'push', ...
    'Text', DisplayNames.uiopt_ok );
ConfirmButton.Layout.Row = 1; ConfirmButton.Layout.Column = 2;

% ---------- CancelButton ----------
CancelButton = uibutton( GridLayoutButtons, 'push', ...
    'Text', DisplayNames.uiopt_cancel, ...
    'ButtonPushedFcn', @(~,~) close(UIFigure) );
CancelButton.Layout.Row = 1; CancelButton.Layout.Column = 3;