function [ UIFigure, CMapDropDown, CLimButtonGroup, CLimCoeffLabel, ...
    MaxLabel, MinLabel, TempAxe, CLimCoeffEdit, ...
    MaxEdit, MinEdit, CLimSlider, ColorBar, CLimPanel, ...
    CMapLabel, AllStageCheckBox ] = ...
    createStyleButton_UI( app )


DisplayNames = app.OtherDisplayNames( app.Default.LanguageSelection );
% ButtonSize = app.ConstantValues.TextedButtonSize;
DropDownHeight = app.ConstantValues.DropDownHeight;
EditSize = [50,30];
UIFigureSize = [300,275];
PanelHeight = 200;
SliderHeight = 50;
LabelWidth = 60;
ColorBarWidth = 60;

% ---------- UIFigure ----------
UIFigure = uifigure( ...
    'Name', DisplayNames.StyleButton_UIFigure, ...
    'WindowStyle', 'alwaysontop', ...alwaysontop
    'Icon', app.ConstantValues.IconSource, ...
    'Resize', 'off', ...
    'UserData', struct( 'ProjectIndex', 0, 'VariableName', '' ) );
UIFigure.Position = getMiddlePosition( ...
    app.UIFigure.Position, UIFigureSize );

% ---------- GridLayoutMain ----------
GridLayoutMain = uigridlayout( UIFigure, ...
    'RowHeight',    { DropDownHeight, PanelHeight, '1x' }, ...
    'ColumnWidth',  { '1x', ColorBarWidth }, ...
    'Padding',      15*ones(1,4));

% ---------- GridLayoutCMapDropDown ----------
GridLayoutCMapDropDown = uigridlayout(  GridLayoutMain, ...
    'RowHeight',    { '1x' }, ...
    'ColumnWidth',  { LabelWidth, '1x' }, ...
    'ColumnSpacing', 15, ...
    'Padding',      0*ones(1,4));
GridLayoutCMapDropDown.Layout.Row = 1;

% ---------- CMapLabel ----------
CMapLabel = uilabel( GridLayoutCMapDropDown, ...
    'Text', DisplayNames.StyleButton_CMapLabel, ...
    'HorizontalAlignment', 'right' );
CMapLabel.Layout.Column = 1;

% ---------- CMapDropDown ----------
CMapNames = app.ConstantValues.ColormapsNames;
CMapDropDown = uidropdown( GridLayoutCMapDropDown , ...
    "Items", CMapNames, ...
    'ItemsData', 1:length(CMapNames), ...
    'Value', app.Default.Options.DICColormapIndex );
CMapDropDown.Layout.Column = 2;

% ---------- CLimPanel ----------
CLimPanel = uipanel( GridLayoutMain, ...
    "Title", DisplayNames.StyleButton_CLimPanel );
CLimPanel.Layout.Row = 2;
CLimPanel.Layout.Column = 1;

% ---------- GridLayoutCLimPanel ----------
GridLayoutCLimPanel = uigridlayout( CLimPanel, ...
    'RowHeight',    { 20, EditSize(2), EditSize(2), SliderHeight, '1x' }, ...
    'ColumnWidth',  { '1x', EditSize(1)-20, '1x', EditSize(1) }, ...
    'Padding',      10*ones(1,4) );

% ---------- CLimButtonGroup ----------
CLimButtonGroup = uibuttongroup( GridLayoutCLimPanel, ...
    'BorderType', 'none' );
CLimButtonGroup.Layout.Row = 1;
CLimButtonGroup.Layout.Column = [1,4];

% ---------- AutoRadioButton ----------
AutoRadioButton = uiradiobutton( CLimButtonGroup, ...
    'Text', DisplayNames.StyleButton_AutoRadioButton, ...
    'UserData', 'auto' );
AutoRadioButton.Position(2) = 0;

% ---------- ManualRadioButton ----------
ManualRadioButton = uiradiobutton( CLimButtonGroup, ...
    'Text', DisplayNames.StyleButton_ManualRadioButton, ...
    'UserData', 'manual' );
ManualRadioButton.Position(1) = CLimButtonGroup.Position(3)*0.4;
ManualRadioButton.Position(2) = 0;

% ---------- CLimCoeffLabel ----------
CLimCoeffLabel = uilabel( GridLayoutCLimPanel, ...
    'Text', DisplayNames.StyleButton_CLimCoeffLabel, ...
    'HorizontalAlignment', 'right', ...
    'WordWrap', 'on' );
CLimCoeffLabel.Layout.Column = 1;
CLimCoeffLabel.Layout.Row = 2;

% ---------- CLimCoeffEdit ----------
CLimCoeffEdit = uieditfield( GridLayoutCLimPanel, 'numeric', ...
    'Value', 10 );
CLimCoeffEdit.Layout.Column = 2;
CLimCoeffEdit.Layout.Row = 2;

% ---------- MaxLabel ----------
MaxLabel = uilabel( GridLayoutCLimPanel, ...
    'Text', DisplayNames.StyleButton_MaxLabel, ...
    'HorizontalAlignment', 'right', ...
    'WordWrap', 'on' );
MaxLabel.Layout.Column = 3;
MaxLabel.Layout.Row = 2;

% ---------- MaxEdit ----------
MaxEdit = uieditfield( GridLayoutCLimPanel, 'numeric', ...
    'Value', 0 );
MaxEdit.Layout.Column = 4;
MaxEdit.Layout.Row = 2;

% ---------- MinLabel ----------
MinLabel = uilabel( GridLayoutCLimPanel, ...
    'Text', DisplayNames.StyleButton_MinLabel, ...
    'HorizontalAlignment', 'right', ...
    'WordWrap', 'on' );
MinLabel.Layout.Column = 3;
MinLabel.Layout.Row = 3;

% ---------- MinEdit ----------
MinEdit = uieditfield( GridLayoutCLimPanel, 'numeric', ...
    'Value', 0 );
MinEdit.Layout.Column = 4;
MinEdit.Layout.Row = 3;

% ---------- AllStageCheckBox ----------
AllStageCheckBox = uicheckbox( GridLayoutCLimPanel, ...
    'Text', DisplayNames.StyleButton_AllStageCheckBox );
AllStageCheckBox.Layout.Column = [1,2];
AllStageCheckBox.Layout.Row = 3;

% ---------- CLimSlider ----------
CLimSlider = uislider( GridLayoutCLimPanel, 'range' );
CLimSlider.Layout.Row = 4;
CLimSlider.Layout.Column = [1,4];
% CLimSlider.Layout.Column = 2;


% ---------- TempAxe ----------
TempAxe = uiaxes( GridLayoutMain, 'Visible', 'off' );
TempAxe.Layout.Row = [1,3];
TempAxe.Layout.Column = 2;
TempAxe.Toolbar.Visible = 'off';

ColorBar = colorbar( TempAxe, 'Units', 'pixels', ...
    'AxisLocation', 'in', ...
    'Position', [ 225, 22, 25, 200 ], ...
    'FontName', 'Times New Roman', ...
    'FontSize', 12 );