function val = EulerAngle2TransferMatrix( Angles )
% obtain transfer matrixes from Euler angles
% G ( sample to crystal )
% Angles : ( 1*3 ) , val : ( 3*3 )
% Angles in rad

phi1 = Angles(1); PHI = Angles(2); phi2 = Angles(3);

val = [ cos(phi1).* cos(phi2) - sin(phi1).* sin(phi2).* cos(PHI) , ...
        sin(phi1).* cos(phi2) + cos(phi1).* sin(phi2).* cos(PHI) , ...
        sin(phi2).* sin(PHI) ; ...
       -cos(phi1).* sin(phi2) - sin(phi1).* cos(phi2).* cos(PHI) , ...
       -sin(phi1).* sin(phi2) + cos(phi1).* cos(phi2).* cos(PHI) , ...
        cos(phi2).* sin(PHI) ; ...
        sin(phi1).* sin(PHI) , ...
       -cos(phi1).* sin(PHI) , ...
        cos(PHI) ];