function EBSDData = getEmptyEBSDData()

EBSDData = struct( ...         % ebsd data
            'DisplayName',  '', ...
            'Coords',       [], ...
            'EulerAngles',  [], ...
            'IQ',           [], ...
            'CI',           [], ...
            'GrainID',      [], ...
            'EdgeIndex',    [], ...
            'Phase',        [], ...
            'PhaseNames',   {''}, ...
            'HCPPhase',     [], ...
            'FCCPhase',     [], ...
            'BCCPhase',     [], ...
            'IPF',          {[]}, ...
            'XData',        [], ...
            'dX',           [], ...
            'YData',        [], ...
            'dY',           [], ...
            'AlphaData',    [], ...
            'Serial',       0, ...
            'Map',          ebsd.map.empty, ...
            'PolyInfo',     '', ...
            'Flag',         struct( 'Adjusted',     false, ...
                                    'Polygonized',  false ), ...
            'Adjust',       struct( 'PointCoords',  [], ...
                                    'tform',        [], ...
                                    'R',            []), ...
            'DataSize',     [], ...
            'GrainGroup', struct('Name','','Index',[],'Serial',[]), ...
            'GrainGroupSerial', 0, ...
            'GrainGroupSelection', 0, ...
            'GrainSelection',[], ...
            'FrontierDev',  0, ...
            'DICSelection', 'exx', ...
            'OriginalFileName', '', ...
            'PreprocessMethod','', ...
            'PreprocessPars', struct(), ...
            'MemorySize', 0, ...
            'SampleCoordOri', struct('X',[0,1],'Y',[-1,0]) );