function IPFAxe = getIPFAxe( )


ThetaRange = pi / 6;

IPFlegendFig = figure( ...
    'Name',         'IPF legend', ...
    'NumberTitle',  'off', ...
    'Color',        [1,1,1] );
IPFlegendFig.Position(3:4) = [ 600, 400 ];

IPFAxe = axes( IPFlegendFig, ...
    'Box',      'off', ...
    'Color',    [1,1,1], ...
    'NextPlot', 'add');
IPFAxe.XAxis.Visible = 'off';
IPFAxe.YAxis.Visible = 'off';


axis( IPFAxe, 'equal' );

theta = 0 : 0.02 : ThetaRange ;
r = ones( size( theta ) );
[ x, y ] = pol2cart( theta, r );
plot( IPFAxe, [0,x,0], [0,y,0], ...
    'Color', 'black', 'LineWidth', 1 );

text( IPFAxe, ...
    'String',   '0001', ...
    'Position', [ -0.1, -0.1 ], ...
    'FontSize', 18  );
text( IPFAxe, ...
    'String',   '2-1-10', ...
    'Position', [ 1-0.1, -0.1 ], ...
    'FontSize', 18  );
text( IPFAxe, ...
    'String',   '10-10', ...
    'Position', [ 0.766, 0.6 ], ...
    'FontSize', 18  );