function [ UIFigure, ...
    SelectFilesButton, FileFormatDropdown, PreprocessMethodDropdown, ...
    PreprocessParametersListbox, ConfirmButton, ...
    FileTable, PreprocessInfoTextArea, PreprocessParametersTable ] ...
    = createDIC_UI( ...
        FileFormatSelection, PreprocessMethod, app )

DisplayNames = app.OtherDisplayNames( app.Default.LanguageSelection );
ButtonSize = app.ConstantValues.TextedButtonSize;

MagnifiedFontSize = 13;

% -------/// CREATE INTERFACE ///-------

% ---------- UIFigure ----------
UIFigure = uifigure( ...
    'Name', DisplayNames.DICImport_UIFigure, ...
    'WindowStyle', 'alwaysontop', ...alwaysontop
    'Icon', app.ConstantValues.IconSource, ...
    'Resize', 'off' );
UIFigure.Position = getMiddlePosition( app.UIFigure.Position, ...
    app.ConstantValues.DICImport_UIFigure_size );


% ---------- GridLayoutMain ----------
GridLayoutMain = uigridlayout( UIFigure, ...
    'RowHeight',    { '5x', ButtonSize(2) }, ...
    'ColumnWidth',  { '1x', '1x' } );


% ---------- FilePanel ----------
FilePanel = uipanel( GridLayoutMain, ...
    'Title', DisplayNames.DICImport_FilePanel_Title );
FilePanel.Layout.Row = 1:2; FilePanel.Layout.Column = 1;


% ---------- GridLayoutFilePanel ----------
GridLayoutFilePanel = uigridlayout( FilePanel, ...
    'RowHeight',    { ButtonSize(2), '4x' }, ...
    'ColumnWidth',  { ButtonSize(1), '1x' } );


% ---------- SelectFilesButton * ----------
SelectFilesButton = uibutton( GridLayoutFilePanel, 'push', ...
    'Text', DisplayNames.DICImport_SelectFilesButton_Text );
SelectFilesButton.Layout.Row = 1;
SelectFilesButton.Layout.Column = 1;


% ---------- GridLayoutFileFormat ----------
GridLayoutFileFormat = uigridlayout( GridLayoutFilePanel, ...
    'RowHeight',    { '1x' }, ...
    'ColumnWidth',  { app.ConstantValues.LabelSize(1), '1x' }, ...
    'Padding', zeros(1,4) );
GridLayoutFileFormat.Layout.Row = 1;
GridLayoutFileFormat.Layout.Column = 2;


% ---------- FileFormatLabel ----------
FileFormatLabel = uilabel( GridLayoutFileFormat, ...
    'Text', DisplayNames.DICImport_FileFormatLabel_Text );
FileFormatLabel.Layout.Column = 1;


% ---------- FileFormatDropdown * ----------
FileFormatDropdown = uidropdown( GridLayoutFileFormat, ...
    'Items', app.DICFileFormats, ...
    'FontSize', MagnifiedFontSize );
FileFormatDropdown.ValueIndex = FileFormatSelection;
FileFormatDropdown.Layout.Column = 2;


% ---------- FileTable ----------
FileTable = uitable( GridLayoutFilePanel, ...
    'ColumnName', '', ...
    'ColumnEditable', false, ...
    'RowName', [], ...
    'FontSize', MagnifiedFontSize );
FileTable.Layout.Row = 2; FileTable.Layout.Column = 1:2;


% ---------- PreprocessPanel ----------
PreprocessPanel = uipanel( GridLayoutMain, ...
    'Title', DisplayNames.DICImport_PreprocessPanel_Title );
PreprocessPanel.Layout.Row = 1; PreprocessPanel.Layout.Column = 2;


% ---------- GridLayoutPreprocessPanel ----------
GridLayoutPreprocessPanel = uigridlayout( PreprocessPanel, ...
    'RowHeight',    { ...
    ButtonSize(2), app.ConstantValues.LabelSize(2), ...
    '1x', app.ConstantValues.LabelSize(2), '1x' }, ...
    'ColumnWidth',  { '1x' } );


% ---------- GridLayoutPreprocessMethod ----------
GridLayoutPreprocessMethod = uigridlayout( GridLayoutPreprocessPanel, ...
    'RowHeight',    { '1x' }, ...
    'ColumnWidth',  { app.ConstantValues.LabelSize(1), '1x' }, ...
    'Padding', zeros(1,4) );
GridLayoutPreprocessMethod.Layout.Row = 1;


% ---------- PreprocessMethodLabel ----------
PreprocessMethodLabel = uilabel( GridLayoutPreprocessMethod, ...
    'Text', DisplayNames.DICImport_PreprocessMethodLabel_Text );
PreprocessMethodLabel.Layout.Column = 1;


% ---------- PreprocessMethodDropdown * ----------
PreprocessMethodNames = struct2cell( structfun( @(obj) ...
    obj.Name, app.DICPreprocessMethods , ...
    'UniformOutput', false ) );
PreprocessMethodDropdown = uidropdown( GridLayoutPreprocessMethod, ...
    'Items', PreprocessMethodNames, ...
    'ItemsData', fieldnames( app.DICPreprocessMethods ), ...
    'FontSize', MagnifiedFontSize );
PreprocessMethodDropdown.Value = PreprocessMethod;
PreprocessMethodDropdown.Layout.Column = 2;


% ---------- PreprocessParametersLabel ----------
PreprocessParametersLabel = uilabel( GridLayoutPreprocessPanel, ...
    'Text', DisplayNames.DICImport_PreprocessParametersLabel_Text );
PreprocessParametersLabel.Layout.Row = 2;


% ---------- GridLayoutPreprocessParameters ----------
GridLayoutPreprocessParameters = uigridlayout( GridLayoutPreprocessPanel, ...
    'RowHeight',    { '1x' }, ...
    'ColumnWidth',  { '1x','1x' }, ...
    'Padding', zeros(1,4) );
GridLayoutPreprocessParameters.Layout.Row = 3;


% ---------- PreprocessParametersListbox * ----------
Parameters = app.DICPreprocessMethods.( PreprocessMethod ).Parameters;

PreprocessParametersListbox = uilistbox( GridLayoutPreprocessParameters, ...
    'Items', Parameters, ...
    'FontSize', MagnifiedFontSize );

if ~isempty( PreprocessParametersListbox.Items )
    PreprocessParametersListbox.Value = Parameters{1};
end

PreprocessParametersListbox.Layout.Column = 1;


% ---------- PreprocessParametersTable ----------
PreprocessParametersTable = uitable( GridLayoutPreprocessParameters, ...
    'ColumnName', '', ...
    'ColumnEditable', true, ...
    'FontSize', MagnifiedFontSize );
PreprocessParametersTable.Layout.Column = 2;


% ---------- PreprocessInfoLabel ----------
PreprocessInfoLabel = uilabel( GridLayoutPreprocessPanel, ...
    'Text', DisplayNames.DICImport_PreprocessInfoLabel_Text );
PreprocessInfoLabel.Layout.Row = 4;


% ---------- PreprocessInfoTextArea ----------
PreprocessInfoTextArea = uitextarea( GridLayoutPreprocessPanel, ...
    'Editable', 'off', ...
    'FontSize', MagnifiedFontSize );
PreprocessInfoTextArea.Layout.Row = 5;


% ---------- GridLayoutButtons ----------
GridLayoutButtons = uigridlayout( GridLayoutMain, ...
    'RowHeight',    { '1x' }, ...
    'ColumnWidth',  { '1x', ButtonSize(1), ButtonSize(1) }, ...
    'Padding', zeros(1,4) );
GridLayoutButtons.Layout.Row = 2;
GridLayoutButtons.Layout.Column = 2;


% ---------- ConfirmButton * ----------
ConfirmButton = uibutton( GridLayoutButtons, 'push', ...
    'Text', DisplayNames.uiopt_ok, ...
    'Enable', 'off' );
ConfirmButton.Layout.Row = 1; ConfirmButton.Layout.Column = 2;


% ---------- CancelButton ----------
CancelButton = uibutton( GridLayoutButtons, 'push', ...
    'Text', DisplayNames.uiopt_cancel, ...
    'ButtonPushedFcn', @(~,~) close(UIFigure) );
CancelButton.Layout.Row = 1; CancelButton.Layout.Column = 3;