function getConstants(app)
%
% UIControlDisplayNames / OtherDisplayNames / ConstantValues

VERSION = getVersion();

% ------------- UIControlDisplayNames -------------
app.UIControlDisplayNames = struct( ...
    'UIFigure', {['DIC Analyzer ',VERSION],['DIC分析软件 ',VERSION]}, ...1
    'ProjectMenu',{'Project','项目'}, ...2 /// Project ///
    'ProjectNewMenu',{'New','新建'}, ...
    'ProjectOpenMenu',{'Open','打开'}, ...
    'ProjectSaveMenu',{'Save','保存'}, ...
    'ProjectClearMenu',{'Clear','清空'}, ...
    'OptionsMenu',{'Options','选项'}, ... /// Options ///
    'DICPreprocessCalculationMethodMenu',{'Preprocess Method','预处理方法'}, ...
    'DICFileFormatMenu',{'File Format','文件格式'}, ...
    'DICColormapMenu',{'Colormap','颜色图'}, ...
    'EBSDPolygonizeMenu',{'Polygonize','多边形化'}, ...
    'GBSmoothDegreeMenu',{'GB Smooth Degree','晶界平滑度'}, ...
    'MinimumGrainSizeMenu',{'Minimum Grain Size','最小晶粒尺寸'}, ...
    'ParallelComputingMenu',{'Parallel Computing','并行计算'}, ...
    'CLimCoeffMenu',{'Color Limits Coefficient','颜色范围系数'}, ...
    'DICShowAxesMenu',{'Show Axes (μm)','显示坐标轴 (μm)'}, ...
    'EBSDShowAxesMenu',{'Show Axes (μm)','显示坐标轴 (μm)'}, ...
    'ValueRangesMenu',{'Value Range Estimation','值范围估计'}, ...
    'PlotMenu', {'Plot','绘图'}, ...
    'GBStyleMenu',{'GB','晶界'}, ...
    'OverlayOpacityMenu',{'Overlay Opacity','叠加图透明度'}, ...
    'MaxResolutionMenu', {'Max Resolution','最大分辨率'}, ...
    'LanguageMenu', {'Language','语言'}, ...
    'ChineseMenu', {'Chinese','中文'}, ...
    'EnglishMenu', {'English','英文'}, ...
    'ExportMenu', {'Export','导出'}, ... /// Export ///
    'ExportImagesMenu', {'Images','图像'}, ...
    'ExportCurvesMenu', {'Curves Data','曲线数据'}, ...
    'ExportDataMenu',{'Data','数据'}, ...
    'ExportEBSDDataangMenu',{'EBSD Data (.ang)','EBSD数据（.ang）'}, ...
    'ExportABAQUSinputfileinpMenu', ...
        {'ABAQUS input file (.inp)', 'ABAQUS输入文件（.inp）'}, ...
    'ExtensionsMenu',{'Extensions','拓展'}, ...
    'DebugMenu',{'Debug','调试'}, ...
    'AppNameLabel', {'DIC Analyzer','DIC分析软件 '}, ...
    'OverlayDICButton', {'Overlay DIC','叠加DIC'}, ...
    'OverlayPolygons', {'Grain Polygons','晶粒多边形'}, ...
    'StageDropDownLabel', {'Stage','阶段'}, ...
    'LabelsCheckBox',{'Labels','晶粒编号'}, ...
    'InteriorCheckBox',{'Interior','内部'}, ...
    'FrontierCheckBox',{'Frontier','边缘'}, ...
    'IntrinsicCheckBox',{'Intrinsic','固有'}, ...
    'NeighboursCheckBox',{'Neighbours','相邻晶粒'}, ...
    'GBsCheckBox',{'GBs','晶界'}, ...
    'GrainLabelsStyleMenu',{'Grain Labels','晶粒编号'}, ...
    'PolygonizeLabel',{'Polygonize','多边形化'}, ...
    'AdjustLabel',{'Data Mapping','数据映射'}, ...
    'ShowButton',{'Show','显示'}, ...
    'GBsSmoothButton',{'Smooth','平滑'}, ...
    'LineStyleColorLabel',{'Color','颜色'}, ...
    'LineStyleStyleLabel',{'Style','线型'}, ...
    'LineStyleWidthLabel',{'Width','线宽'}, ...
    'StatisticalIntervalsLimitsLabel',{'Limits','范围'}, ...
    'StatisticalIntervalsNumberLabel',{'Number','数量'}, ...
    'ImagesTab',{'DIC','DIC'}, ... ************
    'Images2Tab',{'EBSD','EBSD'}, ...
    'ValueTab',{'Probe Values','测量值'}, ...
    'FrequencyTab',{'Frequency Statistics','频率统计'}, ...
    'GrainSelectionPanel',{'Grain Selection','晶粒选择'}, ...
    'BoundaryPanel',{'Boundary','界面'}, ...
    'DICPanel',{'DIC','DIC'}, ...
    'GrainsTab',{'Grains','晶粒'}, ...
    'CurvesTab',{'Curves','曲线'}, ...
    'LineStylePanel',{'Line Style','曲线样式'}, ...
    'AxisSettingsPanel',{'Axis Settings','坐标区设置'}, ...
    'StatisticalIntervalsPanel',{'Statistical Intervals','统计区间'} ...
    );
i = find( strcmp( 'ImagesTab', fieldnames( app.UIControlDisplayNames ) ) );
app.UIControlDisplayNamesIndex = ...
    { 1, 2: i-1, i:length(fieldnames(app.UIControlDisplayNames(1))) };

% ------------- OtherDisplayNames -------------
app.OtherDisplayNames = struct( ...
    'uiopt_yes',{'Yes','是'}, ...
    'uiopt_no',{'No','否'}, ...
    'uiopt_ok',{'OK','确定'}, ...
    'uiopt_cancel',{'Cancel','取消'}, ...
    'uiopt_select',{'Select File','选择文件'}, ...
    'uiopt_complete',{'Complete','完成'}, ...
    'uiopt_export',{'Export','导出'}, ...
    'uiopt_add',{'Add','添加'}, ...
    'uiopt_apply',{'Apply','应用'}, ...
    'uiopt_close',{'Close','关闭'}, ...
    'ui_select',{'Select','选择'}, ...
    'ui_cal',{'Calculate','计算'}, ...
    'error',{'Error','错误'}, ...
    'all',{'All','全选'}, ...
    'invalidvalue_title',{'Invalid value','值无效'}, ...
    'UIFigureCloseRequestuiconfirm_msg', ...
        {'Do you want to close the App?','要关闭软件吗？'}, ...
    'UIFigureCloseRequestuiconfirm_title',{'Close App','关闭软件'}, ...
    'cm_Rename',        {'Rename','重命名'}, ...
    'cm_Name',          {'Name','名称'}, ...
    'cm_New',           {'Create New Project','生成新项目'}, ...
    'cm_DataMeasure',   {'Data Measure','数据测量'}, ...
    'cm_Delete',        {'Delete','删除'}, ...
    'cm_Import',        {'Import','导入'}, ...
    'cm_Modify',        {'Modify','修改'}, ...
    'cm_Calculate',     {'Calculate','计算'}, ...
    'cm_Clear',         {'Clear','清空'}, ...
    'cm_Adjust',        {'Data Mapping','数据映射'}, ...
    'cm_Polygonize',    {'Polygonize','多边形化'}, ...
    'cm_Max',           {'Max','最大'}, ...
    'cm_Min',           {'Min','最小'}, ...
    'cm_CLim',          {'Color Limits','颜色范围'}, ...
    'cm_OverlayOpacity',{'Overlay Opacity','叠加图透明度'}, ...
    'cm_UIAxesDisplay', {'Display Miniature','小窗显示'}, ...
    'cm_UIAxesDisplay_Message', {'Copying images ...','正在复制图像...'}, ...
    'cm_UIAxesDisplay2',{'Display Independent','独立显示'}, ...
    'RenameMenuSelectedFcn_prompt',{'Enter new name:','输入新名称：'}, ...
    'DeleteMenuSelectedFcn_uiconfirm_msg',{'Are you sure to delete','确定删除'}, ...
    'DeleteMenuSelectedFcn_uiconfirm_msg2',{' selected data',' 个选择的数据'}, ...
    'ProjectNewMenuSelectedFcn_prompt',{' Project Name:','项目名称：'}, ...
    'CLimCoeffMenuSelectedFcn_prompt',{'Color Limits Coefficient:','颜色范围系数：'}, ...
    'OverlayOpacityMenuSelectedFcn_prompt', ...
        {'EBSD plot transparency when stacking DIC plots:', ...
        '叠加DIC绘图时EBSD绘图透明度：'}, ...
    'ValueRangesMenuSelectedFcn_prompt',{{'Displacement:','Strain:'},{'位移：','应变：'}}, ...
    'ClearButtonPushedFcn_uiconfirm_msg', ...
        {'Are you sure you want to delete all projects?','确定删除所有项目？'}, ...
    'MaxResolutionMenuSelectedFcn_prompt', ...
        {'Maximum size in one dimension:','单个维度上最大尺寸：'}, ...
    'DICImport_UIFigure',{'Import DIC Data','导入DIC数据'}, ... /// DICImport ///
    'DICImport_FilePanel_Title',{'DIC Files','DIC文件'}, ...
    'DICImport_FileFormatLabel_Text',{'Format','文件格式'}, ...
    'DICImport_PreprocessPanel_Title',{'Pre-process Method','数据预处理'}, ...
    'DICImport_SelectFilesButton_Text',{'Select Files','选择文件'}, ...
    'DICImport_PreprocessMethodLabel_Text',{'Method','方法'}, ...
    'DICImport_PreprocessParametersLabel_Text',{'Parameters','参数'}, ...
    'DICImport_PreprocessInfoLabel_Text',{'Description','说明'}, ...
    'DICImport_uiprogressdlg_Message',{'Loading ... ','正在读取 ... '}, ...
    'DICImport_uiprogressdlg_Message2',{'Preprocessing data','进行数据预处理'}, ...
    'DICClearMenuSelectedFcn_uiconfirm_msg',{'Delete all DIC data?','删除所有DIC数据？'}, ...
    'EBSDImport_UIFigure',{'Import EBSD Data','导入EBSD数据'}, ... /// EBSDImport ///
    'EBSDImport_FilePanel_Title',{'EBSD Files','EBSD文件'}, ...
    'EBSDImport_PreprocessPanel_Title',{'Data Process Method','数据处理'}, ...
    'UIAxesDisplayIndependent_UIFigure',{'Independent Dispaly','独立显示'}, ...
    'Figure', {'Figure','图窗'}, ...
    'Adjust_DICSelectionLabel_Text',{'DIC','DIC'}, ...
    'Adjust_EBSDSelectionLabel_Text',{'EBSD','EBSD'}, ...
    'Adjust_SelectionLabel_Text',{'Homology Points','同源点'}, ...
    'Adjust_SelectButton_Text',{'Add','添加'}, ...
    'Adjust_SelectButton_Text_2',{'Next','下一步'}, ...
    'Adjust_Complete',{'Complete','完成'}, ...
    'Adjust_TextArea_Value_1', ...
        {'Select a point in DIC figure.','在DIC图窗内选择点。'}, ...
    'Adjust_TextArea_Value_2', ...
        {'Select a point in EBSD figure.','在EBSD图窗内选择点。'}, ...
    'GBSmoothDegreeMenuSelectedFcn_prompt', ...
        {'GB Smooth Degree (3~10):','晶界平滑度（3~10）：'}, ...
    'MinimumGrainSizeMenuSelectedFcn_prompt', ...
        {'Minimum Grain Size (pixels)(>=1):','最小晶粒尺寸（像素）（>=1）：'}, ...
    'EBSD2PolygonizeMenuSelectedFcn_uiconfirm_msg', ...
        {'Overwrite the current result?','覆盖当前结果？'}, ...
    'GBStyleMenu_UIFigure',{'GB Style','晶界样式'}, ...
    'GrainLabelsStyleMenu_UIFigure',{'Grain Labels Style','晶粒编号样式'}, ...
    'LineWidthLabel_Text',{'Line Width','线宽'}, ...
    'FontSizeLabel_Text',{'Font Size','字号'}, ...
    'ColorLabel_Text',{'Color','颜色'}, ...
    'GrainSelection_UIFigure',{'Add Grain Selection','添加晶粒选择'}, ...
    'GrainSelection_TypeButtonGroup_Title',{'Selection type','选择类型'}, ...
    'GrainSelection_NumberButton_Text',{'Grain ID','晶粒编号'}, ...
    'GrainSelection_PhaseButton_Text',{'Phase','相'}, ...
    'ProjectSave_UIFigure',{'Save Projets','保存项目'}, ...
    'ProjectSave_ProjectLabel_Text',{'Select projets:','选择项目：'}, ...
    'ProjectSave_dlg',{'Saving ','正在保存 '}, ...
    'ProjectOpen_Text',{'Open Projects','打开项目'}, ....
    'ProjectOpen_dlg',{'Loading ','正在加载 '}, ...
    'plotEBSDGrainLabels_Message',{'Adding grain labels ...','正在添加晶粒编号...'}, ...
    'MainNewMenu_IncludeDICCheckBox_Text',{'Include DIC data','包含DIC数据'}, ...
    'MainNewMenu_MethodButtonGroup_Title',{'Data Source','数据来源'}, ...
    'MainNewMenu_ManualButton_Text',{'Manual selection','手动选择'}, ...
    'MainNewMenu_EBSDDataLabel_Text',{'EBSD Data:','EBSD数据：'}, ...
    'MainNewMenu_OptionPanel_Title',{'Options','选项'}, ...
    'MainNewMenu_IncludeOtherGrainsCheckBox_Text',{'Include other grains','包含其他晶粒'}, ...
    'MainNewMenu_PaddingCheckBox_Text',{'Padding (%)','边缘（%）'}, ...
    'MainNewMenu_uialert_Message',{'Plot an image first','请先绘制图像'}, ...
    'ExportDataMenu_UIFigure',{'Export Data','导出数据'}, ...
    'ExportABAQUSinputfileinpMenu_UIFigure', {'Export ABAQUS input file','导出ABAQUS输入文件'}, ...
    'ExportDataMenu_ContentLabel_Text',{'Select Content:','选择内容：'}, ...
    'ExportDataMenu_UsePolygonizedCheckBox_Text', ...
        {'Use polygonized grain IDs','使用多边形化后晶粒ID'}, ...
    'ExportDataMenu_EBSDPanel_Title',{'EBSD Data','EBSD 数据'}, ...
    'ExportDataMenu_DICPanel_Title',{'DIC Data','DIC 数据'}, ...
    'ExportDataMenu_ExportDICSeparatelyCheckBox_Text', ...
        {'Export DIC data separately','单独导出DIC数据'}, ...
    'ExportDataMenu_BoundaryOnlyCheckBox_Text', ...
        {'Export only the data on the boundary','只导出边界上数据'}, ...
    'ExportDataMenu_FormatButtonGroup_Title',{'File Format','文件格式'}, ...
    'ExportEBSDDataangMenu_TemplateLabel_Text',{'Template','模板'}, ...
    'ExportEBSDDataangMenu_TemplateButton_uigetfile', ...
        {'Select template file','选择模板文件'}, ...
    'plotEBSDGBs_Message', ...
        {'Adding grain boundaries ...','正在添加晶界...'}, ...
    'MaximumElementNumber_Text', ...
        {'Maximum number of rows/columns:','最大行列数：'}, ...
    'ExportDataMenu_DICStageLabel_text', {'Stage:','阶段：'}, ...
    'StyleButton_UIFigure', {'Color Style','颜色样式'}, ...
    'StyleButton_CMapLabel', {'Color Map','颜色图'}, ...
    'StyleButton_CLimPanel', {'Color Limit','颜色范围'}, ...
    'StyleButton_AutoRadioButton', {'Auto','自动'}, ...
    'StyleButton_ManualRadioButton', {'Manual','手动'}, ...
    'StyleButton_CLimCoeffLabel', {'Coefficient','系数'}, ...
    'StyleButton_MaxLabel', {'Max','最大'}, ...
    'StyleButton_MinLabel', {'Min','最小'}, ...
    'StyleButton_AllStageCheckBox', {'all stages','所有阶段'}, ...
    'DICCalculateMenu_UIFigure', {'DIC Data Calculate','DIC数据计算'}, ...
    'StatisticButton_UIFigure', {'Add Statistical Curves','添加统计曲线'}, ...
    'StatisticButton_MethodLabel', {'Method','方法'}, ...
    'StatisticButton_VariableLabel', {'Variable','变量'}, ...
    'StatisticButton_IncludePanel', {'Include','包含'}, ...
    'StatisticButton_PhasesCheckBox', {'Phases','相'}, ...
    'StatisticButton_WholeCheckBox', {'Whole','全部'}, ...
    'StatisticButton_SelectRadioButton', {'Manual Select','手动选择'}, ...
    'StatisticButton_StyleLabel', {'Style','样式'}, ...
    'StatisticButton_WholeRadioButton', {'Whole Reigon','全部范围'}, ...
    'StatisticButton_StageCheckBox', {'All stages','所有阶段'}, ...
    'StatisticButton_GrainPartitionCheckBox', {'Grain partition','晶粒剖分'}, ...
    'MonitorButton_UIFigure', {'Data Monitior','数据监测'}, ...
    'ExportCurves_UIFigure',{'Export Curves Data', '导出曲线数据'}, ...
    'ExportCurves_CurvesLabel', {'Select curves:','选择曲线：'}, ...
    'StatisticButton_GrainPartitionShowCheckBox', {'Show reigons','显示区域'}, ...
    'DICCalculateMenu_BasicLabel', {'Basic:','基础:'}, ...
    'DICCalculateMenu_BESDBasedLabel', {'EBSD based:','基于EBSD:'} );

% ------------- TextAreaStrings -------------
app.TextAreaStrings = struct( ...
    'FilePath', {'File Path: ','文件路径：'}, ...
    'FileName', {'File Names: ','文件名：'} );
    


% ------------- ConstantValues -------------
app.ConstantValues = struct( ...
    'IconSource', 'TJU_logo.png', ...
    'IconedButtonSize', [40,35], ...
    'PullButtonSize', [25,20], ...
    'LeftPanelWidth',  250, ...
    'RightPanelWidth', 350, ...
    'AppNameHeight', 30, ...
    'SuccessImage', 'ok.png', ...
    'EmptyImage', 'ellipsis.png', ...
    'FailImage',  'no.png' );

app.ConstantValues.EBSDDirections = ... axes of sample coord
    {'X','Y','Z'};
app.ConstantValues.DICVariables = ... disp & strain
    {'u','v','exx','eyy','exy'};
app.ConstantValues.DICVariableNames = struct( ...
    'u',    { 'Displacement X', '位移-X' }, ...
    'v',    { 'Displacement Y', '位移-Y' }, ...
    'exx',  { 'Normal Strain X', '正应变-X' }, ...
    'eyy',  { 'Normal Strain Y', '正应变-Y' }, ...
    'exy',  { 'Shear Strain XY', '剪应变-XY' } );

app.ConstantValues.EBSDVariables = ... disp & strain
    {'IPF','IQ','CI','GrainID','EdgeIndex','Phase'};
app.ConstantValues.EBSDVariableNames = struct( ...
    'Coords',  {'Coordinates','坐标'}, ...
    'EulerAngles',  {'Euler Angles','欧拉角'}, ...
    'IPF',    { 'IPF', '反极图' }, ...
    'IQ',     { 'Image Quality', '图像质量' }, ...
    'CI',     { 'Confidence Index', '置信指数' }, ...
    'GrainID',{ 'Grain', '晶粒' }, ...
    'EdgeIndex',{ 'Edge Index', '边缘指数' }, ...
    'Phase',  { 'Phase', '相' } );

% -------- COLORMAPS --------
app.ConstantValues.ColormapsNames = { 
    'parula', 'jet', 'gray', 'hot', ...
    'viridis', 'plasma', 'cividis', ...
    'bwr' };
app.ConstantValues.Colormaps = cellfun( @(name) slanCM( name ), ...
    app.ConstantValues.ColormapsNames, 'UniformOutput', false );
app.ConstantValues.ColormapsNames = [ app.ConstantValues.ColormapsNames, ...
    'b2p', 'b2o' ];
app.ConstantValues.Colormaps = [ app.ConstantValues.Colormaps, ...
    min( TheBestColor( 'akun',92,'map',256 ) * 1.0430, 1 ), ...
    flip(TheBestColor('akun',96,'map',256)) ];

% parula / turbo / hsv / hot / cool / spring / summer / autumn / winter
% gray / bone / copper / pink / sky / abyss / jet

% -------- EXTENSIONS --------
app.ConstantValues.ExtensionNames = { 'OriPF' };


app.ConstantValues.DefaultProjectName = 'Project';
app.ConstantValues.TextedButtonSize = [80,35];
app.ConstantValues.LabelSize = [50,15];
app.ConstantValues.EditSize = [50,30];
app.ConstantValues.DropdownWidth = 200;
app.ConstantValues.DropDownHeight = 30;
app.ConstantValues.SliderHeight = 50;
app.ConstantValues.Tree2Height = 150;

app.ConstantValues.TabGroup2Height = 300;

app.ConstantValues.PlotStyle_UIFigure_size = [240,100];
app.ConstantValues.GrainSelection_UIFigure_size = [160,240];

% ---/// DIC -------------------

app.ConstantValues.DICImport_UIFigure_size = [750,400];

% ---/// EBSD -------------------

app.ConstantValues.EBSDImport_UIFigure_size = [450,600];

% ---/// Independent Display -------------------
app.ConstantValues.IndependentDisplay_UIFigure_size = [800,600];


% ------------------------------------


% ------------- TREE -------------
app.TreeNodeTypes = struct( ...
    'Main', {'Project','Project'}, ...
    'DIC', {'DIC Data','DIC 数据'}, ...
    'EBSD', {'EBSD Data','EBSD 数据'}  );

% ------------- ContextMenu -------------
app.TreeContextMenuTypes.Main = {'Rename','New','Delete'};
app.TreeContextMenuTypes.DIC = {'Import','Modify','Calculate','Clear'};
app.TreeContextMenuTypes.DICData = {'Delete'};
app.TreeContextMenuTypes.EBSD = {'Import','Clear'};
app.TreeContextMenuTypes.EBSD2 = {'Rename','Adjust','Polygonize','Delete'};
app.TreeContextMenuTypes.GrainGroup = {'Delete'};

