function getUserMaterialFormats(app)

UserMaterialFormats = struct( ...
    'OXFORD_UMAT', struct( ...
            'Name', 'OXFORD-UMAT', ...
            'fun',  @ UserMaterialFormats_OXFORD_UMAT ), ...
    'OXFORD_UMAT_250423_1', struct( ...
            'Name', 'OXFORD-UMAT 250423_1', ...
            'fun',  @ UserMaterialFormats_OXFORD_UMAT_250423_1 ), ...
    'OXFORD_UMAT_250603', struct( ...
            'Name', 'OXFORD_UMAT 250603', ...
            'fun',  @ UserMaterialFormats_OXFORD_UMAT_250603 ), ...
    'method_2', struct( ...
            'Name', 'Method-2', ...
            'fun',  @ UserMaterialFormats_method_2 ) ...
            );

UserMaterialFormats.OXFORD_UMAT.Info = { ...
    'OXFORD-UMAT, Parameters are defined in the UMAT file', ...
    '1~3: Euler Angles', '4: Grain ID', ...
    '5: Material ID, 2-FCC / 3-HCP' };
UserMaterialFormats.OXFORD_UMAT_250423_1.Info = { ...
    'OXFORD-UMAT, Parameters are provided in ''User Material'' of material definition', ...
    'Values are the same as those in ''cpfem_hcp_fcc_Zr_250423_1.f'''};
UserMaterialFormats.OXFORD_UMAT_250603.Info = { ...
    'OXFORD-UMAT, Parameters are provided in ''User Material'' of material definition', ...
    'Values are the same as those in ''cpfem_hcp_fcc_Ti_250603.f'''};
UserMaterialFormats.method_2.Info = {'LMQ250220'};


app.ConstantValues.UserMaterialFormats = UserMaterialFormats;