function Value = getDICInfo( DIC )


n = @ num2str; r = @ round;
[ filepath, name, ext ] = fileparts( DIC.FileNames );
Size = size(DIC.Data(1).u);
Value = ...
    [ [ '* File path: ', filepath{1} ], ...
      [ '* File names: ', ...
            arrayfun( @(i) horzcat(name{i},ext{i}), ...
                1:DIC.FileNumber, 'UniformOutput', false ) ], ...
      '* Size: ', ...
      [n(Size(1)),' rows / ', ...
       n(Size(2)),' columns / ', ...
       n(prod(Size)),' pixels' ], ...
      ['* Memory usage: ',n(r(DIC.MemorySize,1)),' MB'], ...
      ['* Time consumed: ',n(r(DIC.TimeSpent,1)),' s'], ...
       '* Data value range estimations:'];

Names = fieldnames( DIC.DataValueRange );
str = '';
for i = 1:length(Names)
    str = [ str, ...
            Names{i},': ', ...
            num2str( DIC.DataValueRange.(Names{i}) ),' / ' ];
end
Value = [ Value, str ];

% if ~isempty( DIC.DispRatio )
%     Value = [ Value, ...
%         '* Displacement Ratio: ', ...
%         [ 'u: ', num2str( DIC.DispRatio(1) ),' µm/pixel / v: ', num2str( DIC.DispRatio(2) ),' µm/pixel'] ];
% else
%     Value = [ Value, '* Displacements are in the unit of PIXEL!' ];
% end
Value = [ Value, ['* Preprocess method: ', DIC.PreprocessMethod] ];
Names = fieldnames( DIC.PreprocessPars );
for i = 1:length(Names)
    Value = [ Value, ...
        [Names{i},': ', ...
        num2str( DIC.PreprocessPars.(Names{i})' )] ];
end


