function plotEBSDGBs( app, EBSDData )


delete( app.GBsPlot )


% GrainSelection = EBSDData.GrainSelection;
ind = strcmp( app.GBsDropDown.Value, {EBSDData.GrainGroup.Name} );
GrainSelection = EBSDData.GrainGroup(ind).Index;

if app.Default.Options.GrainsTab.Neighbours
    fun = @(i) find( [EBSDData.Map.grains.ID] == i );
    % GrainSelection = unique( [ GrainSelection, arrayfun( fun, ...
    %     unique( vertcat(EBSDData.Map.grains( GrainSelection ).neighbours) ) )' ]);
    GrainSelection = unique( [ GrainSelection, cell2mat(arrayfun( fun, ...
            unique( vertcat(EBSDData.Map.grains( GrainSelection ).neighbours) ), ...
            'UniformOutput', false ))' ]);
end

if length(GrainSelection) > 100
    dlg = uiprogressdlg(app.UIFigure,'Indeterminate','on');
    dlg.Title = app.UIControlDisplayNames(app.Default.LanguageSelection). ...
        GBsCheckBox;
    dlg.Message = app.OtherDisplayNames( app.Default.LanguageSelection ). ...
        plotEBSDGBs_Message;
end

app.GBsPlot = EBSDData.Map.plotgb( ...
    GrainSelection, ...
    app.UIAxesImages2, ...
    app.Default.Options.GBColor, ...
    app.Default.Options.GBLineWidth, ...
    app.GBsSmoothButton.Value );