function plotEBSDGrainLabels( app, EBSDData )


delete( app.GrainLabels )

GrainSelection = EBSDData.GrainSelection;
if app.Default.Options.GrainsTab.Neighbours
    fun = @(i) find( [EBSDData.Map.grains.ID] == i );
    % GrainSelection = unique( [ GrainSelection, arrayfun( fun, ...
    %     unique( vertcat(EBSDData.Map.grains( GrainSelection ).neighbours) ) )' ]);
    GrainSelection = unique( [ GrainSelection, cell2mat(arrayfun( fun, ...
            unique( vertcat(EBSDData.Map.grains( GrainSelection ).neighbours) ), ...
            'UniformOutput', false ))' ]);
end

if length(GrainSelection) > 100
    dlg = uiprogressdlg(app.UIFigure,'Indeterminate','on');
    dlg.Title = app.UIControlDisplayNames(app.Default.LanguageSelection). ...
        LabelsCheckBox;
    dlg.Message = app.OtherDisplayNames( app.Default.LanguageSelection ). ...
        plotEBSDGrainLabels_Message;
end

app.GrainLabels = EBSDData.Map.overlayGrainLabels( ...
    GrainSelection, ...
    app.UIAxesImages2, ...
    app.Default.Options.GrainLabelsColor, ...
    app.Default.Options.GrainLabelsFontSize );
