function OldEnableStates = setUIsOff( app )

UINames = { ...
    'ProjectMenu', 'OptionsMenu', 'ExportMenu', ...
    'Tree', 'Tree2', ...
    'StageDropDown', 'StageDropDownLabel', 'EBSDDropDown', 'EBSDDropDownLabel', ...
    'ButtonFold', 'TextArea', 'OverlayDICButton', 'OverlayPolygons', ...
    'GrainSelectionPanel', 'BoundaryPanel', 'DICPanel' };
    % 'OpenButton', 'HideButton', 'ClearButton', 'AddPlotButton', ...
OldEnableStates = cellfun( @(name) ...
    app.(name).Enable, UINames, 'UniformOutput', false );
cellfun( @(name) set( app.(name), 'Enable', 'off' ), UINames );

% cellfun( @(name) set( app.(name), 'Visible', 'off' ), ...
%     { 'TabGroup', 'UIAxesImages3' } );