function setUIsOn( OldEnableStates, app )


UINames = { ...
    'ProjectMenu', 'OptionsMenu', 'ExportMenu', ...
    'Tree', 'Tree2', ...
    'StageDropDown', 'StageDropDownLabel', 'EBSDDropDown', 'EBSDDropDownLabel', ...
    'ButtonFold', 'TextArea', 'OverlayDICButton', 'OverlayPolygons', ...
    'GrainSelectionPanel', 'BoundaryPanel', 'DICPanel' };
    % 'OpenButton', 'HideButton', 'ClearButton', 'AddPlotButton', ...
arrayfun( @(i) ...
    set( app.(UINames{i}), 'Enable', OldEnableStates{i} ), ...
    1:length(UINames) );

% cellfun( @(name) set( app.(name), 'Visible', 'on' ), ...
%     { 'TabGroup', 'UIAxesImages3' } );