function EBSD = EBSDPreprocess_Reimport( EBSD, dlg )
%
%
%    ----- DIRECTLY USE 'Method_AssignColumn' -----

Pars = struct( ...
    'Column_Coords',        [1,2]',     ...
    'Column_EulerAngles',   [3,4,5]',   ...
    'Column_IQ',            9,          ...
    'Column_CI',            6,          ...
    'Column_GrainID',       8,          ...
    'Column_EdgeIndex',     0,         ...
    'Column_PhaseName',     [10,nan]' ,  ...
    'AngleUnit',            'rad'       ...
    );

EBSD.PreprocessPars = Pars;
EBSD = EBSDPreprocess_Method_AssignColumn( EBSD, dlg );