function EBSD = EBSDPreprocess_Format_OIM( EBSD, dlg )
%
%
%    ----- DIRECTLY USE 'Method_AssignColumn' -----

Pars = struct( ...
    'Column_Coords',        [4,5]',     ...
    'Column_EulerAngles',   [1,2,3]',   ...
    'Column_IQ',            6,          ...
    'Column_CI',            7,          ...
    'Column_GrainID',       9,          ...
    'Column_EdgeIndex',     10,         ...
    'Column_PhaseName',     [11,12]' ,  ...
    'AngleUnit',            'rad'       ...
    );

EBSD.PreprocessPars = Pars;
EBSD = EBSDPreprocess_Method_AssignColumn( EBSD, dlg );