function [ FCC_PhaseNames, BCC_PhaseNames, HCP_PhaseNames ] ...
    = getPhaseNames()


FCC_PhaseNames = { ...
    'TitaniumHydride', 'Austenite', 'Ferrite', 'Iron(Epsilon)', ...
    'TiH2', '2', '0', 'Nickel', 'ZrH2-FCC' };
BCC_PhaseNames = { ...
    'Fe(alpha,' };
HCP_PhaseNames = { 'Titanium(Alpha)', 'Fe(epsilon,','Ti-HCP', ...
    'Zirconium(Alpha)', '1', 'Zr', 'Zr(alpha)' };