function createGrainSelectionTreeNodes( EBSDData, app )

% Tree Nodes
delete( app.GrainSelectionTree.Children )

Nodes = arrayfun(@(gp) ...
    uitreenode( app.GrainSelectionTree, ...
        'Text', gp.Name, ...
        'UserData', gp.Index, ...
        'NodeData', gp.Serial, ...
        'ContextMenu', app.TreeContextMenu.GrainGroup), ...
        EBSDData.GrainGroup );

app.GrainSelectionTree.CheckedNodes = ...
         app.GrainSelectionTree.Children( ...
         arrayfun(@(i)find(i==[Nodes.NodeData]), ...
         EBSDData.GrainGroupSelection) );

app.GBsDropDown.Items = {EBSDData.GrainGroup.Name};
app.GBsDropDown.Value = app.GBsDropDown.Items{1};