function save( obj, path, v )


obj.TreeNodes = struct( ... % in 'app.Tree'
            'Main', [], ...
            'DIC', [], ...
            'DICData', [], ...
            'EBSD', [], ...
            'EBSD2', [], ...
            'EBSDData', [] );
obj.Tree2Nodes = [];

obj.StatisticResults = arrayfun( @(sr) ...
    setfield( sr, 'Nodes', [] ), obj.StatisticResults );

save( [path, '\', obj.DisplayName,'.mat'], 'obj', v )
% , '-v7.3' 